title: Lakewood Cafe
description: Here are the guides!
theme: just-the-docs

url: https://dennissmolders09.github.io/Lakewood-Cafe

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/https://github.com/dennissmolders09/hii
